### ISSUE TITLE
InfluencerList 

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#1]
## Value statement - a requirement, not a solution

As a marketing manager
I want to see influencer profiles 
so that I can find the right collaboration partner

## Description (Text, Scribble, Wireframe, Design)

A list of influencer profiles with important details

![InfluencerList](https://user-images.githubusercontent.com/57952428/91828825-eb6be400-ec40-11ea-88ca-d71be2ee5bf7.png)

## Acceptance criteria

- [x]  implement as shown in wireframe

## Tasks

- [x] Create feature branch

- [x] Create InfluencerList component in Storybook

- [x] Write InfluencerList component tests

- [x] Add components to app (feature implementation with state)

- [x] Add missing styles

## Complexity

small

**Comment by annidrumm** [comment]
closed this in #4
