### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#10]
## Value statement - a requirement, not a solution
As a marketing manager
I want to contact influencer 
so that I can collaborate with them

## Description (Text, Scribble, Wireframe, Design)

With the contact button you can send out an email

<img width="390" alt="contact" src="https://user-images.githubusercontent.com/57952428/92928612-a06f7f00-f43f-11ea-8024-eb888fdf5db0.png">

## Acceptance criteria

- [x] Contact button leads to mail

## Tasks
- [x] Create feature branch

- [x] Create ContactButton component

- [x] Add ContactButton to storybook

- [x] Test ContactButton

- [x]  Add components to app (feature implementation with state)

## Size
small

**Comment by annidrumm** [comment]
solved in  #15
