### ISSUE TITLE
Save favourites

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#11]
## Value statement - a requirement, not a solution
As a marketing manager
I want to save my favourite profiles
so that I can easily make decisions which one will fit best for a collaboration

## Description (Text, Scribble, Wireframe, Design)

Save your favourite influencer and find all favourites on one click.

![favourites](https://user-images.githubusercontent.com/57952428/92463959-bf1a0f80-f1cc-11ea-97ca-10986d64d230.png)

## Acceptance criteria

- [x] Add or remove your favourites

- [x] See all favourites on one click

- [x] Change url to /favourites

## Tasks
- [x] Create feature branch

- [x] Create FavouriteButton component

- [x] Add FavouriteButton to storybook

- [x] Test FavouriteButton

- [x] Save locally, load and filter to /favourites

- [x] Create Nav component

- [x] Add Nav to storybook

- [x] Test Nav component

- [x]  Add components to app (feature implementation with state)

- [x] Update Test App 

## Size
medium

**Comment by annidrumm** [comment]
solved in #13
