### ISSUE TITLE
Filter more

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#12]
## Value statement - a requirement, not a solution
As a marketing manager
I want to find an influencer for a specific gender, location, follower amount
so that I can collaborate with a person for a specific budget

## Description (Text, Scribble, Wireframe, Design)

![Filter](https://user-images.githubusercontent.com/57952428/92358359-a97fe980-f0e9-11ea-9ab5-9f4392effe42.png)

## Tasks
- [ ] Create feature branch

- [ ] Create menu

- [ ] Filter gender, location, follower amount

- [ ] Test menu, filter

- [ ] Add to router

- [ ]  Add components to app (feature implementation with state)

## Size
small
