### ISSUE TITLE
InfluencerForm

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#16]
## Value statement - a requirement, not a solution
I am an influencer
I want to set up a profile
so that I can be found for collaborations

## Description (Text, Scribble, Wireframe, Design)

Navigate to "Set up a profile" and fill out a form, then you will see your new profile.

<img width="1148" alt="Screen Shot 2020-09-24 at 15 55 10" src="https://user-images.githubusercontent.com/57952428/94154608-60b48880-fe7e-11ea-8b10-757fef2b601a.png">

## Acceptance criteria
- [x]  URL will change to /create and /profile
- [x] form has required fields, which have to be filled, before the form can be submitted
- [x] by submit /create the form, the profile will be saved
- [x] show abbreviate Number for followers like 12k or 3.5m on your profile

## Tasks
- [x] Create feature branch

- [x] Create NavigationPage in storybook

- [x] Create CreateProfile in storybook

- [x] Create Profile

- [x]  Add components to app (feature implementation with state)

- [x] Write tests

- [x] Write cypress test

## Size
medium

**Comment by annidrumm** [comment]
solved in #19
