### ISSUE TITLE
Delete-Profile

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#17]
## Value statement - a requirement, not a solution
I am an influencer 
I want to delete my profile
so that I can remove my data

## Description (Text, Scribble, Wireframe, Design)

![Screen Shot 2020-09-23 at 22 45 10](https://user-images.githubusercontent.com/57952428/94067993-e7ba2000-fdee-11ea-940b-e251452d8d88.png)

## Acceptance criteria
- [ ] Delete Button deletes profile

## Tasks

- [ ] Create delete button in Profile component in Storybook

- [ ] Write delete function

- [ ] Write  component tests

- [ ]  Add components to app (feature implementation with state)

## Size
small
