### ISSUE TITLE
CategoryPage

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#2]
## Value statement - a requirement, not a solution

As a marketing manager 
I want to find an influencer for a specific category
so that I can collaborate with a person who fits to the project/product 

## Description (Text, Scribble, Wireframe, Design)

A category page which directs you to a list of all influencer

<img width="959" alt="Categories" src="https://user-images.githubusercontent.com/57952428/92126315-51eb3080-ee00-11ea-9f6e-c8b2e8f73112.png">

## Acceptance criteria

- [x]  Click on a category to show a list from all influencer profiles 

- [x]  Click the go back button (<) to see the CategoryPage again

- [x] URL will show in which category you are for example / or /InfluencerList

## Tasks

- [x] Create feature branch

- [x] Create CategoryButton component in Storybook

- [x] Write CategoryButton component tests

- [x] Create CategoryPage component in Storybook

- [x] Write CategoryPage component tests

- [x] Add react-router

- [x] Create Headline component in Storybook

- [x] Write Headline component tests

- [x] Add components to app (feature implementation with state)

- [x] Add missing styles

## Size
medium

**Comment by LebkuchenCJ** [comment]
Hey, it looks very nice already. GJ 💯 two thoughts on your styling (maybe too early, sorry :) ), but: 
1)
If you remove the standard padding from the UL, your list will move more into the middle which creates a nicer reading. 
![image](https://user-images.githubusercontent.com/68224104/92222383-3b47e680-ee9f-11ea-9b3c-0216c0889be0.png)

2) If you open your app on non-mobile screen it´s stretched over the whole screen and won`t look that nice. You can give it a margin on any screen size over VALUE=X (similar to the the following example from the spiegel.de) Again. Maybe this is too early and you might have on your mind already.
![image](https://user-images.githubusercontent.com/68224104/92222951-0d16d680-eea0-11ea-8704-7e83d4444adb.png)

**Comment by annidrumm** [comment]
Styling tips are always welcome and helpful. Thanks a lot :-)

**Comment by annidrumm** [comment]
solved this in #5
