### ISSUE TITLE
Style FavouritePage

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#24]
## Value statement - a requirement, not a solution
As user
I want to see a difference between "Browse" and "Favourite" page
so that I don´t get confused on what page I am

## Acceptance criteria
- [x] new style for FavouritePage

## Tasks
- [x]  Create FavouritePage component in Storybook

- [x] Write component tests

- [x] Add components to app (feature implementation with state)

- [x]  Create Design elements in Storybook

## Size
small

**Comment by annidrumm** [comment]
solved in #25
