### ISSUE TITLE
Profile-pictures

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#3]
## Value statement - a requirement, not a solution

I am a marketing manager
I want to find Influencer based on their pictures/content
so that I can see if the person will fit to our project/product

## Description (Text, Scribble, Wireframe, Design)

This page will have a profile picture and a headline

![ProfilePic](https://user-images.githubusercontent.com/57952428/91840058-5bce3180-ec50-11ea-81ed-7ccfcf03c691.png)

## Acceptance criteria

- [x] Add profile pictures

## Tasks

- [x] Create feature branch

- [x] Add image path

- [x] Display image

- [x] Add components to app (feature implementation with state)

- [x] Add missing styles

## Size
small

**Comment by karstenlenz** [comment]
Your images are very high-resolution (4000x6000px!), but the display size is only 150x220px. You should reduce the file size and upload it again. For Retina displays 300x440px should be enough.  Then the page should load much quicker.

Also you changed the aspect ratio of the picture form 2:3 in the original file to 15:22 which slightly distorts the image. You should probably keep the correct aspect ratio.

**Comment by carolinwagner** [comment]
I just clicked through your app - the pictures are all displayed correctly! Great job :-). 
Though as a user I am a bit confused, because at the moment all influencer are always displayed in the categories "food, fitness, beauty,...", although the single influencer may represent other categories. Since the app should be "finished" after every user story - you might want to pay attention to this in your next story :-)

**Comment by annidrumm** [comment]
solved in #8
