### ISSUE TITLE
StartPage

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#6]
## Value statement - a requirement, not a solution

As a user
I want to see a start screen
so that I know what this app is about and how to use it

## Description (Text, Scribble, Wireframe, Design)

A StartPage which shows information what to expect and a start button to the NavigationPage

<img width="950" alt="Screen Shot 2020-09-24 at 16 40 21" src="https://user-images.githubusercontent.com/57952428/94160206-aecc8a80-fe84-11ea-8b41-f76419ab8767.png">

## Acceptance criteria

- [x] Start button goes to NavigationPage
- [x] URL will change from / to /navigate

## Tasks

- [x] Create StartPage component in Storybook

- [x] Write StartPage component tests

- [x] Write component tests

- [x] Write cypress tests

- [x] Add react-router

- [x] Add components to app (feature implementation with state)

- [ ] Add missing styles

## Size

small

**Comment by annidrumm** [comment]
solved in  #20
