### ISSUE TITLE
Filter-categories

### ISSUE THREAD

**Issue by annidrumm** [annidrumm/influencer-finder#7]
## Value statement - a requirement, not a solution

As a marketing manager
I want to find an influencer for a specific category
so that I can collaborate with a person who fits to the project/product

## Description (Text, Scribble, Wireframe, Design)

The CategoryPage which directs you to a list of influencer for a specific category

![FilterCategories](https://user-images.githubusercontent.com/57952428/92221709-2585f180-ee9e-11ea-8efe-04b79b62c214.png)

## Acceptance criteria
- [x] URL will show in which category you are for example / or /food /fitness /beauty /fashion /interior /travel

## Tasks
- [x] Create feature branch

- [x] Create pages – food /fitness /beauty /fashion /interior /travel 

- [x] Filter categories

- [x] Test pages

- [x] Add to router

- [x]  Add components to app (feature implementation with state)

## Size
medium

**Comment by annidrumm** [comment]
solved in #9
